stages:
  - build

build_app:
  stage: build
  image: node:latest
  script:
    - yarn install
    - yarn global add electron-builder
    - yarn dist:win
  artifacts:
    paths:
      - dist/
  only:
    - main