stages:
  - build

build_app:
  stage: build
  image: electronuserland/builder:wine
  script:
    - yarn install
    - yarn global add electron-builder
    - yarn dist:win
  artifacts:
    paths:
      - dist/
  only:
    - main